site_name: Hymple Docs
site_description: Oficial documentation for Hymple
site_author: Hymple Team

theme:
  name: material
  language: en-US

nav:
  - Home: index.md
  - Introduction: introduction.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
