site_name: Hymple Exchange Documentation
site_url: https://hy-mple.github.io/hymple.docs/
use_directory_urls: true

nav:
  - Home: index.md
  - Introdução: introduction.md
  - Primeiros Passos: getting-started.md
  - Trading: trading.md
  - Wallet: wallet.md
  - API: api.md
  - FAQ: faq.md

theme:
  name: material

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html