site_name: Hymple Docs
site_description: Documentação oficial do ecossistema Hymple
site_author: Hymple Team

theme:
  name: material
  language: pt-BR

nav:
  - Home: index.md
  - Introduction: introduction.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
